platform/x86: bitland-mifs-wmi: add CONFIG_LEDS_CLASS dependency
The newly added driver requires the LED classdev support
and causes a link failure when that is disabled:

x86_64-linux-ld: vmlinux.o: in function `bitland_mifs_wmi_probe':
bitland-mifs-wmi.c:(.text+0xede02a): undefined reference to `devm_led_classdev_register_ext'

Fixes: dc1ec4fa86b2 ("platform/x86: bitland-mifs-wmi: Add new Bitland MIFS WMI driver")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
----
There is currently a mix of 'depends on LEDS_CLASS'
and 'select LEDS_CLASS' in the platform drivers. This
is something that should be fixed at some point, as it
risks circular dependencies.

The majority use 'select', but I went for 'depends on'
here since the symbol is user visible.

Link: https://patch.msgid.link/20260519202804.1339581-1-arnd@kernel.org
Reviewed-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>
Signed-off-by: Ilpo Järvinen <ilpo.jarvinen@linux.intel.com>